create table "public"."contact" (
    "id" bigint generated by default as identity not null,
    "email" text not null,
    "phone" text not null,
    "facebook" text not null,
    "instagram" text not null,
    "linkedin" text not null,
    "youtube" text not null,
    "user" bigint not null default '1'::bigint
      );


alter table "public"."contact" enable row level security;


  create table "public"."projects" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "category" text not null,
    "area" numeric not null,
    "cover" text,
    "creation_date" text not null
      );


alter table "public"."projects" enable row level security;

CREATE UNIQUE INDEX contact_pkey ON public.contact USING btree (id);

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

alter table "public"."contact" add constraint "contact_pkey" PRIMARY KEY using index "contact_pkey";

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

grant delete on table "public"."contact" to "anon";

grant insert on table "public"."contact" to "anon";

grant references on table "public"."contact" to "anon";

grant select on table "public"."contact" to "anon";

grant trigger on table "public"."contact" to "anon";

grant truncate on table "public"."contact" to "anon";

grant update on table "public"."contact" to "anon";

grant delete on table "public"."contact" to "authenticated";

grant insert on table "public"."contact" to "authenticated";

grant references on table "public"."contact" to "authenticated";

grant select on table "public"."contact" to "authenticated";

grant trigger on table "public"."contact" to "authenticated";

grant truncate on table "public"."contact" to "authenticated";

grant update on table "public"."contact" to "authenticated";

grant delete on table "public"."contact" to "postgres";

grant insert on table "public"."contact" to "postgres";

grant references on table "public"."contact" to "postgres";

grant select on table "public"."contact" to "postgres";

grant trigger on table "public"."contact" to "postgres";

grant truncate on table "public"."contact" to "postgres";

grant update on table "public"."contact" to "postgres";

grant delete on table "public"."contact" to "service_role";

grant insert on table "public"."contact" to "service_role";

grant references on table "public"."contact" to "service_role";

grant select on table "public"."contact" to "service_role";

grant trigger on table "public"."contact" to "service_role";

grant truncate on table "public"."contact" to "service_role";

grant update on table "public"."contact" to "service_role";

grant delete on table "public"."projects" to "anon";

grant insert on table "public"."projects" to "anon";

grant references on table "public"."projects" to "anon";

grant select on table "public"."projects" to "anon";

grant trigger on table "public"."projects" to "anon";

grant truncate on table "public"."projects" to "anon";

grant update on table "public"."projects" to "anon";

grant delete on table "public"."projects" to "authenticated";

grant insert on table "public"."projects" to "authenticated";

grant references on table "public"."projects" to "authenticated";

grant select on table "public"."projects" to "authenticated";

grant trigger on table "public"."projects" to "authenticated";

grant truncate on table "public"."projects" to "authenticated";

grant update on table "public"."projects" to "authenticated";

grant delete on table "public"."projects" to "postgres";

grant insert on table "public"."projects" to "postgres";

grant references on table "public"."projects" to "postgres";

grant select on table "public"."projects" to "postgres";

grant trigger on table "public"."projects" to "postgres";

grant truncate on table "public"."projects" to "postgres";

grant update on table "public"."projects" to "postgres";

grant delete on table "public"."projects" to "service_role";

grant insert on table "public"."projects" to "service_role";

grant references on table "public"."projects" to "service_role";

grant select on table "public"."projects" to "service_role";

grant trigger on table "public"."projects" to "service_role";

grant truncate on table "public"."projects" to "service_role";

grant update on table "public"."projects" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."contact"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."contact"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."contact"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Enable all for authenticated users only"
  on "public"."projects"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Enable read access for all users"
  on "public"."projects"
  as permissive
  for select
  to public
using (true);



  create policy "Authenticated users can upload 1ffg0oo_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((auth.role() = 'authenticated'::text));



  create policy "Authenticated users can upload 1ffg0oo_1"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using ((auth.role() = 'authenticated'::text));



  create policy "Authenticated users can upload 1ffg0oo_2"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((auth.role() = 'authenticated'::text));



  create policy "Authenticated users can upload 1ffg0oo_3"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using ((auth.role() = 'authenticated'::text));



  create policy "read for everyone 1ffg0oo_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'images'::text));