name: Keep Supabase Running

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API Endpoint
        run: |
          curl -I https://wnetrzahann.vercel.app/projekty
